// Single source for the home view AND the generated SKILL.md (AXI
// principle 7). Edit here; skills/higgsfield-axi/SKILL.md is regenerated by
// `npm run skill:gen` and CI fails if it drifts (`npm run skill:check`).

import { homedir } from "node:os";
import { emitKV, emitList } from "../output/toon.js";
import { helpBlock } from "../output/suggest.js";
import { DEFAULTS, MODELS } from "../catalog/index.js";
import { credsStatus } from "../api/creds.js";

export const DESCRIPTION =
  "Generate images and video via the Higgsfield API and get local file paths back";

export const SPEC_VERSION = "axi/1.0-2026-07";

export function collapseHome(path: string): string {
  const home = homedir();
  return path.startsWith(home) ? "~" + path.slice(home.length) : path;
}

/**
 * Shared body of the home view; `tool` is how commands are written
 * ("higgsfield-axi" live, "npx -y higgsfield-axi" in the static skill).
 * Static content only - the live credentials line is added in renderHome.
 */
export function homeBody(tool: string): string {
  const images = MODELS.filter((m) => m.kind === "image").length;
  const videos = MODELS.filter((m) => m.kind === "video").length;
  const facts = emitKV([
    ["catalog", `${MODELS.length} models (${images} image, ${videos} video)`],
    ["defaults", `image=${DEFAULTS.image} video=${DEFAULTS.video} out=./higgsfield-out`],
  ]);
  const help = helpBlock([
    `${tool} image "<prompt>" --aspect 16:9`,
    `${tool} video "<prompt>" --image <file-or-url>`,
    `${tool} models --kind image`,
    `${tool} wait <request-id>`,
  ]);
  return [facts, help].join("\n");
}

export function renderHome(binPath: string): string {
  const header = `higgsfield-axi: ${collapseHome(binPath)} — ${DESCRIPTION}`;
  const creds = `credentials: ${credsStatus()}`;
  return [header, creds, homeBody("higgsfield-axi")].join("\n");
}

/** Full tool reference for `higgsfield-axi --help`. */
export function rootHelpText(): string {
  const commands = emitList(
    "commands",
    [
      { command: "models [model-id]", summary: "List models or show one model's parameters" },
      { command: "image <prompt>", summary: "Generate images (downloads results by default)" },
      { command: "video <prompt>", summary: "Generate video (downloads results by default)" },
      { command: "status <request-id>", summary: "Show request state and output URLs" },
      { command: "wait <request-id>", summary: "Poll to a terminal state and download outputs" },
      { command: "cancel <request-id>", summary: "Cancel a queued request" },
    ],
    ["command", "summary"],
  );
  const flags = emitList(
    "flags",
    [
      { flag: "--help", default: "", description: "show help for any command" },
      { flag: "--version", default: "", description: "print the tool version" },
    ],
    ["flag", "default", "description"],
  );
  return [
    `higgsfield-axi: ${DESCRIPTION}`,
    commands,
    flags,
    "examples[3]:",
    '  higgsfield-axi image "hero banner, soft gradients" --aspect 16:9',
    '  higgsfield-axi video "slow pan over a workspace" --image ./hero.png',
    "  higgsfield-axi models --kind video",
  ].join("\n");
}

/** The static SKILL.md: home content with zero-install command forms. */
export function renderSkill(): string {
  const frontmatter = [
    "---",
    "name: higgsfield-axi",
    `description: "${DESCRIPTION.replace(/"/g, "'")}"`,
    "---",
  ].join("\n");
  const body = [
    "# higgsfield-axi",
    "",
    `${DESCRIPTION} (built against AXI spec ${SPEC_VERSION}). Run the commands below with npx — no install needed.`,
    "",
    "Credentials: set `HF_API_KEY_ID` and `HF_API_KEY_SECRET` (keys from https://cloud.higgsfield.ai), or write them as KEY=VALUE lines to `~/.config/higgsfield-axi/credentials`.",
    "",
    "```",
    homeBody("npx -y higgsfield-axi"),
    "```",
    "",
    "`image`/`video` submit a generation, poll to completion, download outputs, and print local file paths (`--no-wait` to just get the request id). `--ref`/`--image` accept local files (uploaded automatically) or URLs. `models <model-id>` shows every parameter a model accepts; pass extras with `--params '{...}'`.",
    "",
    "Every command supports `--help`. Exit codes: 0 success/no-op, 1 error, 2 usage error. All output is TOON on stdout.",
  ].join("\n");
  return [frontmatter, "", body, ""].join("\n");
}
