// Single source for the home view AND the generated SKILL.md (AXI
// principle 7). Edit here; skills/higgsfield-axi/SKILL.md is regenerated by
// `npm run skill:gen` and CI fails if it drifts (`npm run skill:check`).

import { homedir } from "node:os";
import { emitKV, emitList } from "../output/toon.js";
import { fixBlock, helpBlock } from "../output/suggest.js";
import type { CliStatus } from "../hf/exec.js";
import { CATALOG_BLURB, DEFAULT_MODELS } from "../hf/defaults.js";

export const DESCRIPTION =
  "Generate images, video, and more by wrapping the official Higgsfield CLI, and get local file paths back";

export const SPEC_VERSION = "axi/1.0-2026-07";

export function collapseHome(path: string): string {
  const home = homedir();
  return path.startsWith(home) ? "~" + path.slice(home.length) : path;
}

function cliStatusLine(status: CliStatus): string {
  if (!status.installed) return "not installed";
  return status.version ? `installed (${status.version})` : "installed";
}

function authStatusLine(status: CliStatus): string {
  if (!status.installed) return "unknown (install the CLI first)";
  if (status.authenticated === undefined) return "unknown";
  return status.authenticated ? "authenticated" : "not authenticated";
}

/**
 * Shared body of the home view; `tool` is how commands are written
 * ("higgsfield-axi" live, "npx -y higgsfield-axi" in the static skill).
 */
export function homeBody(tool: string, status: CliStatus): string {
  const facts = emitKV([
    ["higgsfield-cli", cliStatusLine(status)],
    ["auth", authStatusLine(status)],
    ["catalog", CATALOG_BLURB],
  ]);
  if (!status.installed) {
    // fix[], not help[]: these are commands for a different program, and
    // AXI tooling that discovers subcommands from help[] blocks would
    // otherwise mistake e.g. "install" for a subcommand of this tool.
    const fix = fixBlock(["npm install -g @higgsfield/cli", "brew install higgsfield-ai/tap/higgsfield"]);
    const help = helpBlock([`${tool} models`, `${tool} image "<prompt>" --model ${DEFAULT_MODELS.image}`]);
    return [facts, fix, help].join("\n");
  }
  if (!status.authenticated) {
    const fix = fixBlock(["higgsfield auth login"]);
    const help = helpBlock([`${tool} models`]);
    return [facts, fix, help].join("\n");
  }
  const help = helpBlock([
    `${tool} image "<prompt>" --model ${DEFAULT_MODELS.image}`,
    `${tool} video "<prompt>" --model ${DEFAULT_MODELS.video}`,
    `${tool} models --kind image`,
    `${tool} wait <job-id>`,
  ]);
  return [facts, help].join("\n");
}

export function renderHome(binPath: string, status: CliStatus): string {
  const header = `higgsfield-axi: ${collapseHome(binPath)} — ${DESCRIPTION}`;
  return [header, homeBody("higgsfield-axi", status)].join("\n");
}

/** Full tool reference for `higgsfield-axi --help`. */
export function rootHelpText(): string {
  const commands = emitList(
    "commands",
    [
      { command: "models [model-id]", summary: "List models or show one model's parameters" },
      { command: "image <prompt>", summary: "Generate images (downloads results by default)" },
      { command: "video <prompt>", summary: "Generate video (downloads results by default)" },
      { command: "status <job-id>", summary: "Show job state and output URLs" },
      { command: "wait <job-id>", summary: "Poll to completion and download outputs" },
    ],
    ["command", "summary"],
  );
  const flags = emitList(
    "flags",
    [
      { flag: "--help", default: "", description: "show help for any command" },
      { flag: "--version", default: "", description: "print the tool version" },
    ],
    ["flag", "default", "description"],
  );
  return [
    `higgsfield-axi: ${DESCRIPTION}`,
    commands,
    flags,
    "requires[1]:",
    "  the official Higgsfield CLI (`higgsfield`, npm i -g @higgsfield/cli) - see: https://github.com/higgsfield-ai/cli",
    "examples[3]:",
    '  higgsfield-axi image "hero banner, soft gradients" --aspect_ratio 16:9',
    '  higgsfield-axi video "slow pan over a workspace" --start-image ./hero.png',
    "  higgsfield-axi models --kind video",
  ].join("\n");
}

/** The static SKILL.md: describes the wrapper model with zero-install command forms. */
export function renderSkill(): string {
  const frontmatter = [
    "---",
    "name: higgsfield-axi",
    `description: "${DESCRIPTION.replace(/"/g, "'")}"`,
    "---",
  ].join("\n");
  const body = [
    "# higgsfield-axi",
    "",
    `${DESCRIPTION} (built against AXI spec ${SPEC_VERSION}). This tool shells out to the official [Higgsfield CLI](https://github.com/higgsfield-ai/cli) - it does not call the Higgsfield API directly.`,
    "",
    "Install and authenticate the official CLI first (one-time setup this tool depends on):",
    "",
    "```sh",
    "npm install -g @higgsfield/cli   # or: brew install higgsfield-ai/tap/higgsfield",
    "higgsfield auth login",
    "```",
    "",
    "Then run higgsfield-axi with npx - no separate install needed:",
    "",
    "```",
    `higgsfield-axi: ${DESCRIPTION}`,
    emitKV([["catalog", CATALOG_BLURB]]),
    helpBlock([
      `npx -y higgsfield-axi image "<prompt>" --model ${DEFAULT_MODELS.image}`,
      `npx -y higgsfield-axi video "<prompt>" --model ${DEFAULT_MODELS.video}`,
      "npx -y higgsfield-axi models --kind image",
      "npx -y higgsfield-axi wait <job-id>",
    ]),
    "```",
    "",
    "`image`/`video` shell out to `higgsfield generate create <model> --prompt ...`, wait for completion by default, download outputs, and print local file paths (`--no-wait` to just get the job id back). Any flag not shown in `--help` is forwarded verbatim to that underlying call (e.g. `--aspect_ratio`, `--resolution`, `--image-references`, `--duration`) - inspect a model's accepted parameters with `higgsfield-axi models <model-id>` or `higgsfield model get <model-id>`.",
    "",
    "Every command supports `--help`. Exit codes: 0 success/no-op, 1 error, 2 usage error. All output is TOON on stdout. There is no `cancel` command - the underlying Higgsfield CLI does not expose one.",
  ].join("\n");
  return [frontmatter, "", body, ""].join("\n");
}
